OWNER_NAME="𝐊𝐞𝐢𝐭𝐡𝐤𝐞𝐢𝐳𝐳𝐚𝐡"
PREFIX="-"
MODE='private'
AUTO_VIEW_STATUS="on"
AUTO_SAVE_STATUS="off"
BOT_NAME= "𝐇𝐔𝐍𝐂𝐇𝐎-𝐌𝐃"
IMAGE_MENU= "https://telegra.ph/file/e18441d126f37be8efbfa.jpg"
NUMERO_OWNER= ""
OWNER_NAME= "᚛𝐊𝐞𝐢𝐭𝐡 𝐤𝐞𝐢𝐳𝐳𝐚𝐡᚜"
DATABASE_URL= ""
WARN_COUNT= ""
OPENAI_API_KEY= ""
STARTING_BOT_MESSAGE='on'
ANTI_DELETE_MESSAGE='on'
